sudo: required
services:
  - docker

before_install:
  - docker build -t danhv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danhv/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-037914935397"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY